
# HTML before the closing </head>
[params]
customHead = ""

# Navigation
[params.navigation]
logo = "images/logo.png"
home = "Home"
about = "Informazioni"
service = "Funzionalità"
contact = "Contatti"

# Hero Area
[params.hero]
enable = true
bg = "images/header-bg.jpg"
title = "Libera il potenziale della tua ospitalità"
subtitle = "Trasforma i soggiorni turistici in esperienze a 5 stelle con la nostra soluzione di personal concierge. Automatizza le operazioni, aumenta i ricavi e delizia gli ospiti con la sicurezza della blockchain."
btnText = "Entra in lista d'attesa!"

# counter
disableCountdown = false
countdownYear = "2025"
countdownMonth = "09"
countdownDay = "30"

# About Section
[params.about]
enable = true
heading = "Vuoi offrire ai tuoi ospiti un'esperienza 5 stelle guadagnandoci? Vuoi accogliere i viaggiatori senza il pensiero di quanto lasceranno in bolletta?"
description = "In Stay Tips stiamo costruendo la soluzione del futuro che ti permette di offrire ai tuoi ospiti servizi selezionati, rispondere ai loro bisogni senza rispondere ai loro messaggi e risparmiare tempo e risorse aumentando la loro soddisfazione. Non ci credi? se non raggiungiamo i risultati promessi ti rimborsiamo il 100% del tuo investimento"

[[params.about.sliderItem]]
image = "images/about/1.jpg"
[[params.about.sliderItem]]
image = "images/about/2.jpg"
[[params.about.sliderItem]]
image = "images/about/3.jpg"
[[params.about.sliderItem]]
image = "images/about/2.jpg"


# Service Section
[params.service]
enable = true
title = "Riprendi il controllo della tua attività"
subtitle = "La nostra soluzione deriva da anni di esperienza nell'ospitalità e nel turismo, combinata con una visione chiare del futuro."
[[params.service.serviceItem]]
icon = "tf-ion-social-bitcoin-outline"
title = "Pagamenti automatici"
description = "Con Camino i pagamenti sono automatici e garantiti, senza rischi di insolvenza o ritardi."
delay = "0s"

[[params.service.serviceItem]]
icon = "tf-profile-male"
title = "Persone, non sigle"
description = "Ti diciamo con chi stai parlando e ti aiutiamo a rispondere alle domande consapevole della loro cultura."
delay = "0.2s"

[[params.service.serviceItem]]
icon = " tf-genius"
title = "AI e automazione"
description = "L'intelligenza artificiale aiuta a comunicare, anche sui social e ad interfacciarti coi sistemi complessi"
delay = "0.4s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-map-pin"
title = "Tecnologia di prossimità"
description = "usando la posizione degli ospiti possiamo attivare e disattivare servizi e interazioni specifiche"
delay = "0.6s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-ion-network"
title = "Rete di fornitori"
description = "Selezionato i migliori fornitori di servizi per gli ospiti, per garantire costantemente un'esperienza di alta qualità"
delay = "0.8s"

[[params.service.serviceItem]]
icon = "tf-shield2"
title = "Burocrazia e privacy"
description = "I dati sensibili sono protetti e condivisi solo con i servizi della pubblica amministrazione, per garantire la sicurezza degli ospiti e la tua compliance"
delay = "1s"

[[params.service.serviceItem]]
icon = "tf-ion-social-euro-outline"
title = "Contabilità"
description = "tenere i conti in ordine è fondamentale, la nostra soluzione lo fa in automatico e produce già gli output per il commercialista"
delay = "1.2s"

[[params.service.serviceItem]]
icon = "tf-wallet"
title = "Integrato col wallet digitale"
description = "La nuova frontiera dei documenti è rappresentata dal wallet digitale, noi siamo pronti"
delay = "1.5s"

# [[params.service.serviceItem]]
# icon = "tf-ion-paintbucket"
# title = "White Label"
# description = "Per utenti enterprise offriamo la possibilità di avere un'app personalizzata con il tuo logo e colori"
# delay = "1.8s"


# Call to Action Section
[params.cta]
enable = true
bg = "images/call-to-action.jpg"
title = "Entra nel futuro dell'ospitalità"
subtitle = "Lascia i tuoi dati per essere tra i primi a scoprire come Stay Tips può rivoluzionare la tua attività"


[params.architecture]
enable = true
title = "Come è fatta la soluzione"
subtitle = "3 app che comunicano tra loro coordinate da una intelligenza artificiale che si appoggia alla blockchain"
image = "images/architecture.png"
image_webp = "images/architecture.webp"
content = "Ogni applicazione può essere utilizzata su mobile o desktop ed è dedicata ad un utente specifico: l'ospite, il proprietario e il fornitore di servizi. L'intelligenza artificiale semplifica le interazioni con le app, garantendo un'esperienza fluida e personalizzata per tutti gli utenti."

[params.contact]
enable = false
title = "Get In Touch"
subtitle = "Lorem ipsu dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex"

# [caches]
#   [caches.images]
#     dir = ':cacheDir/images'